### ISSUE TITLE
{User interface} Randomly generate matches

### ISSUE THREAD

**Issue by adrianolisboa** [raigons/uaisoccer#10]
**As an user
I want to be able to generate matches between teams randomly
So I can have more accurate and unbiased matches in a faster way**

## Notes
This story is related to the user story #9 

## Acceptance Criteria
Given I have available teams to a championship 
When I generate matches randomly
Then I cannot regenerate them

Given I have available teams to a championship 
When I generate matches randomly
Then I will have a list of matches

**Comment by agdacjm** [comment]
Estória não é prioridade para MPV. Será executada a médio prazo.
