### ISSUE TITLE
Search Javascript APIs / Libs

### ISSUE THREAD

**Issue by adrianolisboa** [raigons/uaisoccer#13]
Find 3 javascript API  / Libs options for the project

**Comment by FFrancieli** [comment]
The following libraries should be considered:

- [Minimalist Javascript](http://www.minjs.com/)
- [Minified](http://minifiedjs.com/#sizeCmp)
- [Director](https://github.com/flatiron/director)

**Comment by FFrancieli** [comment]
João Lucas' suggestions: 

- knokout
- Jasmine
- Mustache
 - underscore
- backbone
- karma (test runner)
- casper js -> functional test
- marionete
