### ISSUE TITLE
{User interface} Configure bootstrap

### ISSUE THREAD

**Issue by adrianolisboa** [raigons/uaisoccer#17]
Configure the bootstrap template with yeoman.

**Comment by raigons** [comment]
:bomb: :fire:  :soccer: (penalty!)

não funciona no Vagrant =/

**Comment by adrianolisboa** [comment]
Tudo está funcionando dentro de Vagrant agora :dancer: :dancers: !

**Comment by raigons** [comment]
@adrianolisboa: te devemos um cerveja (só uma :beer: )
