### ISSUE TITLE
{API} Insert Team Avatar

### ISSUE THREAD

**Issue by luhhsnunes** [raigons/uaisoccer#26]
**As an API consumer
I want to be able to save and retrieve the avatar for a new team
So it can be displayed along the system**

## Out of scope
- Register a new team
- Edit a registered team
- Edit the avatar of a registered team

## Notes
It assumes that the user story #24 has already been played
The avatar is not a required information
*Invalid values for avatar means any value not correspondent to a string. We should also prevent the user of sending "" as a value.

## Acceptance Criteria
Given I am registering a new team
When I POST to `/teams/` with the content:
```json
{ 
    "avatarPath": "images/prods/team.jpg"
}
``` 
Then the API returns the HTTP status code 201 (Created)
And I see the following attribute as part of its body:
```json
{
        "avatarPath": "images/prods/team.jpg"
}
```

Given I am registering a new team
When I POST to `/teams/` with an invalid value* to `avatarPath` attribute
Then the API returns the HTTP status code 400 (Bad Request)

Given I am registering a new team
When I GET to `/teams/1`
Then the API returns the HTTP status code 200 (OK)
And I see the following attribute as part of its body:
```json
{
        "avatarPath": "images/prods/team.jpg"
}
```

**Comment by raqlem** [comment]
Estória não prioritária para MVP
