### ISSUE TITLE
{API} Edit Team Avatar

### ISSUE THREAD

**Issue by agdacjm** [raigons/uaisoccer#27]
**As an API consumer
I want to be able to save and retrieve the team avatar of a registered team
So it can be displayed along the system**

## Out of scope
- Register a new team
- Edit a registered team
- Insert the avatar for a new team
- Delete team avatar

## Notes
It assumes that the user story #24 has already been played
The avatar is not a required information
This story is related to the user story #26

## Acceptance Criteria

Given I am editing a registered team
And a team with id 1 has already been created
When I PUT to `/teams/1` with the content:
```json
{ 
    "avatarPath": "images/prods/new_team_avatar.jpg"
}
``` 
Then the API returns the HTTP status code 200 (OK) 
And I see the response containing the following attribute as part of its body:
```json
{
        "avatarPath": "images/prods/new_team_avatar.jpg"
}
```

Given I am editing a registered team
And the team with id 1 has already been updated
When I GET to `/teams/1`
Then the API returns the HTTP status code 200 (OK)
And I see the response containing the following attribute as part of its body:
```json
{
        "avatarPath": "images/prods/new_team_avatar.jpg"
}
```

**Comment by raqlem** [comment]
Estória não prioritária para MVP

**Comment by raqlem** [comment]
Estória não prioritária para MVP
