### ISSUE TITLE
Refactor keys and IDs for teams

### ISSUE THREAD

**Issue by luhhsnunes** [raigons/uaisoccer#28]
## Tasks
- [ ] Team keys must become IDs
- [ ] IDs must be unique

Given I have registered a team with the following details:
```json
{
    "name": "Atlético Paranaense",
    "key": "atletico-paranaense"
}
``` 
When I attempt to create a new team with the same ```"key": "atletico-paranaense"```
Then I should receive a HTTP409 (Conflict) with the following json:
```json
{
    "success": "false",
    "message": "Duplicated keys are not allowed "
}
```

**Comment by raqlem** [comment]
Resolvido.
