### ISSUE TITLE
{API} Delete Team Avatar

### ISSUE THREAD

**Issue by agdacjm** [raigons/uaisoccer#30]
**As an API consumer
I want to be able to delete the team avatar of a registered team
So it can be changed along the system**

## Out of scope
- Register a new team
- Edit a registered team
- Insert the avatar for a new team
- Edit team avatar

## Notes
The avatar is not a required information
This story is related to the user story #26

## Acceptance Criteria

Given a registered team has a team avatar and I am deleting it
When I DELETE to `/teams/1` with the content:
```json
{ 
    "avatarPath": "images/prods/new_team_avatar.jpg"
}
``` 
Then the API returns the HTTP status code 200 (OK)
And I see the following content as part of its body:
```json
{        
    "avatarPath": null
}
```

Given a registered team has a team avatar and I am deleting it
When I GET to `/teams/1`
Then the API returns the HTTP status code 200 (OK)
And I see the following content as part of its body:
```json
{        
    "avatarPath": null
}
```

**Comment by raqlem** [comment]
Estória não prioritária para MVP
