### ISSUE TITLE
{User interface} Disable an existent team

### ISSUE THREAD

**Issue by FFrancieli** [raigons/uaisoccer#4]
**As an user 
I want to disable a team
So this team cannot be assigned to a championship.**

## Out of scope
Team removal
Team list
Enable a team

## Note
This story is related to the user story #5 
Disabling a team doesn't mean deleting it
Disabling a team is a required information

## Acceptance Criteria

Given that an user is at the Team List page
When she attempts to disable one of the teams
Then the label of the button must change from 'Disable' to 'Enable'
And the disabled team keeps being displayed on the list
And she is able to enable the team again

## Cross-functional Requirements

Double-click: Javascript mush behave properly to avoid multiple requests if the user attempts to click multiple times to disable a team.

**Comment by raqlem** [comment]
Estória não prioritária para MVP
