### ISSUE TITLE
{User interface} List championship

### ISSUE THREAD

**Issue by agdacjm** [raigons/uaisoccer#42]

**Comment by agdacjm** [comment]
**As an user 
I want to be able to list all created championships
So that I can view all championships registered on the system**

## Out of Scope
Create a championship
Edit a championship
Delete a championship
Application wizard with championship details

## Notes
The championship details will be implemented in another story

## Acceptance criteria
Given an existing user
When she logs into the system
And she chooses the option Championship
Then she is able to view the Championship List page with the championship details

Given there is no registered championships
When the user visits the Championship List Page
Then she views the message: "There are no registered championships."

Given there are registered championship on the system 
When the user visits the Championship List Page
Then she views all created championships

Given there are registered championships on the system 
When the user makes some change on the championship status
Then this change must be reflected on the list

Given the user is at the Championship List Page
Then she is not able to view championships that have been deleted from the system

**Comment by raqlem** [comment]
Estória não prioritária para MVP
