### ISSUE TITLE
{User Interface} List teams

### ISSUE THREAD

**Issue by FFrancieli** [raigons/uaisoccer#5]
**As an user 
I want to be able to list the names all registered teams
So that I can use this information to setup new championships**

## Out of Scope
Register a new team
Edit a team
Delete a team
Enable/Disable a team
Team details

## Notes
The Team List page is not the Assign Team to Championship page.
The team details will be implemented in another story

## Acceptance criteria
Given an existing user
When she visits the Home Page
And she chooses the option Team
Then she is able to view the Team List page with the team's name and team's details

Given there is no registered teams
When the user visits the Team List Page
Then she views the message: "There are no registered teams."

Given there are registered teams on the system 
When the user visits the Team List Page
Then she views all the teams' names(enabled and disabled ones)

Given there are registered teams on the system 
When the user makes some change on the team information
Then this change must be reflected on the list

When the user is at the Team List Page
Then she is not able to view teams' names that have been deleted from the system

**Comment by raqlem** [comment]
Estória não prioritária para MVP
