### ISSUE TITLE
{User interface} Remove an existent team

### ISSUE THREAD

**Issue by FFrancieli** [raigons/uaisoccer#7]
**As an user
I want to remove a registered team
So I do not need to deal with a team that is not assigned and will not be assigned to a championship**

## Out of scope 
Edit a team

## Notes
This story is related to the user story #16 and #43 

## Acceptance criteria

Given that a team is not assigned to any championship
When she selects the button "delete" on the teams' line
Then she views the message: "All the team history will be removed from the system. Are you sure to delete this team?"

Given that a team is not assigned to any championship
When she selects the button "delete" on the teams' line
And she proceeds to delete the team
Then she views the message: "The team was successfully deleted."
And the removed team doesn't keep being displayed on the Team List Page

Given that a team is not assigned to any championship
When she she selects the button "delete" on the teams' line
And she doesn't proceed to delete the team
Then she is able to view the Team List Page 
And the team keep being displayed on the Team List Page

Given that a team is assigned to a championship
When she she selects the button "delete" on the teams' line
Then she views the message: "The team can not be deleted because it is assigned to a championship."
And the team keep being displayed on the Team List Page

**Comment by agdacjm** [comment]
Estória fechada, pois não faz parte do MVP. Para o MVP, usaremos apenas a opção de "desabilitar"
