### ISSUE TITLE
{User Interface} Create a championship

### ISSUE THREAD

**Issue by FFrancieli** [raigons/uaisoccer#8]
**As an user 
I want to be able to create a championship
So I can give it a name, select teams and generate matches between them**

## Out of Scope
Edit championship
Delete championship
Application wizard 
Assign teams to a new championship
Generate matches
Championship List page

## Notes
This story is related to the user story #18
The application wizard will be implemented in another story
The Championship List page will be implemented in another story
It is not mandatory to fill all form to create a championship
Championship name is mandatory

## Acceptance criteria
Given an existing user
When she views the Championship List page 
The she is able to select the option "New championship"

Given an existing user
When she select the option "New Championship"
Then she is able to view a form to insert championship details

Given an existing user
When she fill the form at least with Championship's Name
And she selects the button "save"
Then she views the message: "Championship successfully created."
And she is able to view the championship on Championship List page

Given an existing user
When she doesn't fill the form at least with Championship's Name
And she selects the button "save"
Then she views the message: "Championship was not created. You should fill at least the Championship's name."
And she is not able to view the championship on Championship List page

**Comment by agdacjm** [comment]
Estória não é prioridade para MPV. Será executada a médio prazo.
