### ISSUE TITLE
{User interface} Assign teams to a new championship

### ISSUE THREAD

**Issue by FFrancieli** [raigons/uaisoccer#9]
**As an user
I want to be able to assign teams to a new championship
So I can define which teams will enjoy the championship**

## Out of scope
Register a championship
Delete a championship
Edit a championship
Assign teams to a existent championship
Assign teams to a existent championship with ongoing games 
Enable/Disable a team
Application wizard to create a championship

## Notes
This user story is dependent of the user story #8
The Assign Team to Championship page is not the Team List page

## Acceptance Criteria

Given an existing user
When she creates a new championship
Then she is able to view the application wizard with Assign Team to Championship option

Given there is no enable teams
When the user visits the Assign Team to Championship page
Then she views the message: "There are no enable teams."

Given there are enable teams on the system 
When the user visits the Create Championship page
Then she views a list of all enabled teams under the section Assign Teams to Championship
And she is able to mark the checkbox of those that will be part of the championship

Given there are enable teams on the system 
And the user is at the Assign Team to Championship page
When she assigns two teams
And chooses to save the changes  to the championship
Then she views a message: "The teams were successfully assigned." 

Given there are enable teams on the system 
And the user is at the Assign Team to Championship page
When she attempts to save the changes with only one team assigned
Then she views a message: "At least two enable teams must be selected." 

Given there are enable teams on the system 
And the user is at the Assign Team to Championship page
When she attempts to save the changes with no teams assigned
Then she views a message: "At least two enable teams must be selected."

**Comment by raqlem** [comment]
Estória não prioritária para MVP
